package:
  name: pyocct
  version: 7.4.0.0

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [win]
    - cmake
    - ninja

  host:
    - python
    - pybind11
    - occt ==7.4.0
    - smesh ==8.3.0.3
    - tbb-devel

  run:
    - python
    - occt ==7.4.0
    - smesh ==8.3.0.3

test:
  source_files:
    - test

about:
  home: https://github.com/LaughlinResearch/pyOCCT
  license: LGPL2.1
  license_family: LGPL
  summary: Python bindings for OpenCASCADE and SMESH
  description: Python bindings for OpenCASCADE geometry kernel and SMESH meshing library.
